export const UNIVERSITIES = [
  "Abia State University (ABSU)",
  "Abubakar Tafawa Balewa University (ATBU)",
  "Achievers University, Owo",
  "Adamawa State University (ADSU)",
  "Adeleke University, Ede",
  "Adekunle Ajasin University (AAUA)",
  "Afe Babalola University (ABUAD)",
  "African University of Science and Technology (AUST)",
  "Ahmadu Bello University (ABU)",
  "Air Force Institute of Technology (AFIT)",
  "Ajayi Crowther University",
  "Akwa Ibom State University (AKSU)",
  "Al-Hikmah University",
  "Al-Qalam University",
  "Alex Ekwueme Federal University (AE-FUNAI)",
  "Aliko Dangote University of Science and Technology (ADUSTECH)",
  "Ambrose Alli University (AAU)",
  "American University of Nigeria (AUN)",
  "Anchor University, Lagos",
  "Arthur Jarvis University",
  "Augustine University",
  "Babcock University",
  "Bauchi State University (BASUG)",
  "Bayero University Kano (BUK)",
  "Bayelsa Medical University (BMU)",
  "Baze University",
  "Bells University of Technology (BELLSTECH)",
  "Benson Idahosa University (BIU)",
  "Benue State University (BSU)",
  "Bingham University",
  "Borno State University (BOSU)",
  "Bowen University",
  "Caleb University",
  "Caritas University",
  "Chrisland University",
  "Christopher University",
  "Chukwuemeka Odumegwu Ojukwu University (COOU)",
  "Claretian University of Nigeria",
  "Coal City University",
  "Covenant University",
  "Crawford University",
  "Crescent University",
  "Cross River University of Technology (CRUTECH)",
  "Crown Hill University",
  "Delta State University (DELSU)",
  "Dominion University, Ibadan",
  "Dominican University, Ibadan",
  "Ebonyi State University (EBSU)",
  "Edo State University, Uzairue",
  "Edwin Clark University",
  "Ekiti State University (EKSU)",
  "Eko University of Medicine and Health Sciences",
  "Elizade University",
  "Enugu State University of Medical and Applied Sciences (SUMAS)",
  "Enugu State University of Science and Technology (ESUT)",
  "Evangel University",
  "Federal University of Agriculture, Abeokuta (FUNAAB)",
  "Federal University of Agriculture, Makurdi (FUAM)",
  "Federal University of Health Sciences, Azare",
  "Federal University of Health Sciences, Ila-Orangun",
  "Federal University of Health Sciences, Otukpo (FUHSO)",
  "Federal University of Technology, Akure (FUTA)",
  "Federal University of Technology, Babura",
  "Federal University of Technology, Ikot Abasi",
  "Federal University of Technology, Minna (FUTMINNA)",
  "Federal University of Technology, Owerri (FUTO)",
  "Federal University, Birnin Kebbi (FUBK)",
  "Federal University, Dutse (FUDutse)",
  "Federal University, Dutsin-Ma (FUDutsinma)",
  "Federal University, Gashua (FUGA)",
  "Federal University, Gusau (FUGUS)",
  "Federal University, Kashere (FUKashere)",
  "Federal University, Lafia (FULafia)",
  "Federal University, Lokoja (FULokoja)",
  "Federal University, Oye-Ekiti (FUOYE)",
  "Federal University, Wukari (FUWukari)",
  "Federal University of Petroleum Resources, Effurun (FUPRE)",
  "Fountain University, Osogbo",
  "Godfrey Okoye University",
  "Gombe State University (GSU)",
  "Gombe State University of Science and Technology",
  "Gregory University, Uturu",
  "Hallmark University",
  "Hezekiah University",
  "Ibrahim Badamasi Babangida University (IBBU)",
  "Igbinedion University, Okada",
  "Imo State University (IMSU)",
  "James Hope University",
  "Joseph Ayo Babalola University (JABU)",
  "Kaduna State University (KASU)",
  "Kano State University of Science and Technology (KUST)",
  "Kebbi State University of Science and Technology (KSUSTE)",
  "Kings University",
  "Kogi State University (KSU)",
  "Kwara State University (KWASU)",
  "Kwararafa University",
  "Ladoke Akintola University of Technology (LAUTECH)",
  "Lagos State University (LASU)",
  "Lagos State University of Education (LASUED)",
  "Lagos State University of Science and Technology (LASUSTECH)",
  "Landmark University",
  "Lead City University",
  "Legacy University, Okija",
  "Madonna University",
  "Mcpherson University",
  "Mewar International University",
  "Michael Okpara University of Agriculture (MOUAU)",
  "Moshood Abiola University of Science and Technology",
  "Mountain Top University",
  "Nasarawa State University (NSUK)",
  "National Open University of Nigeria (NOUN)",
  "Niger Delta University (NDU)",
  "Nigeria Maritime University, Okerenkoko",
  "Nigerian Defence Academy (NDA)",
  "Nile University of Nigeria",
  "Nnamdi Azikiwe University (UNIZIK)",
  "Novena University",
  "Obafemi Awolowo University (OAU)",
  "Obong University",
  "Oduduwa University",
  "Olabisi Onabanjo University (OOU)",
  "Olusegun Agagu University of Science and Technology (OAUSTECH)",
  "Osun State University (UNIOSUN)",
  "Oyo State Technical University (Tech-U)",
  "Pan-Atlantic University",
  "Paul University, Awka",
  "Philomath University",
  "Plateau State University (PLASU)",
  "Precious Cornerstone University",
  "Redeemer's University",
  "Renaissance University",
  "Rhema University",
  "Ritman University",
  "Rivers State University (RSU)",
  "Salem University",
  "Samuel Adegboyega University",
  "Sokoto State University (SSU)",
  "Southwestern University",
  "Spiritan University",
  "Sule Lamido University (SLU)",
  "Summit University, Offa",
  "Tai Solarin University of Education (TASUED)",
  "Tansian University",
  "Thomas Adewumi University",
  "Trinity University, Lagos",
  "Umaru Musa Yar'Adua University (UMYU)",
  "University of Abuja (UNIABUJA)",
  "University of Benin (UNIBEN)",
  "University of Calabar (UNICAL)",
  "University of Ibadan (UI)",
  "University of Ilorin (UNILORIN)",
  "University of Jos (UNIJOS)",
  "University of Lagos (UNILAG)",
  "University of Maiduguri (UNIMAID)",
  "University of Mkar",
  "University of Nigeria, Nsukka (UNN)",
  "University of Port Harcourt (UNIPORT)",
  "University of Uyo (UNIUYO)",
  "Usmanu Danfodiyo University Sokoto (UDUS)",
  "Veritas University, Abuja",
  "Wellspring University",
  "Wesley University, Ondo",
  "Western Delta University",
  "Westland University",
  "Wigwe University",
  "Yobe State University (YSU)",
  "Zamfara State University (ZASU)",
  "Others"
];

export const FACULTIES = [
  "Faculty of Arts",
  "Faculty of Agriculture",
  "Faculty of Basic Medical Sciences",
  "Faculty of Biological Sciences",
  "Faculty of Clinical Sciences",
  "Faculty of Education",
  "Faculty of Engineering / Technology",
  "Faculty of Environmental Sciences",
  "Faculty of Law",
  "Faculty of Management Sciences",
  "Faculty of Pharmaceutical Sciences",
  "Faculty of Physical Sciences",
  "Faculty of Social Sciences",
  "Faculty of Veterinary Medicine",
  "College of Medicine",
  "Graduate School",
  "Others"
];

export const DEPARTMENTS: Record<string, string[]> = {
  "Faculty of Arts": [
    "English and Literary Studies",
    "History and International Studies",
    "Linguistics and Nigerian Languages",
    "Mass Communication",
    "Philosophy",
    "Religious Studies",
    "Theatre and Film Studies",
    "Music",
    "Fine and Applied Arts"
  ],
  "Faculty of Agriculture": [
    "Agricultural Economics",
    "Agricultural Extension",
    "Animal Science",
    "Crop Science",
    "Soil Science",
    "Food Science and Technology",
    "Fisheries and Aquaculture",
    "Forestry and Wildlife Management"
  ],
  "Faculty of Engineering / Technology": [
    "Agricultural Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Computer Engineering",
    "Electrical and Electronics Engineering",
    "Mechanical Engineering",
    "Materials and Metallurgical Engineering",
    "Mechatronics Engineering",
    "Petroleum and Gas Engineering",
    "Systems Engineering"
  ],
  "Faculty of Physical Sciences": [
    "Computer Science",
    "Mathematics",
    "Physics and Astronomy",
    "Pure and Industrial Chemistry",
    "Geology",
    "Statistics"
  ],
  "Faculty of Biological Sciences": [
    "Biochemistry",
    "Microbiology",
    "Plant Science and Biotechnology",
    "Zoology and Environmental Biology",
    "Genetics and Molecular Biology"
  ],
  "Faculty of Social Sciences": [
    "Economics",
    "Geography",
    "Political Science",
    "Psychology",
    "Sociology and Anthropology",
    "Social Work"
  ],
  "Faculty of Management Sciences": [
    "Accounting",
    "Banking and Finance",
    "Business Administration",
    "Marketing",
    "Public Administration",
    "Entrepreneurial Studies"
  ],
  "Faculty of Education": [
    "Arts Education",
    "Science Education",
    "Social Science Education",
    "Vocational and Technical Education",
    "Educational Foundations",
    "Guidance and Counseling",
    "Library and Information Science"
  ],
  "Faculty of Environmental Sciences": [
    "Architecture",
    "Building",
    "Estate Management",
    "Quantity Surveying",
    "Surveying and Geoinformatics",
    "Urban and Regional Planning"
  ],
  "Faculty of Law": [
    "Public Law",
    "Private and Property Law",
    "Commercial Law",
    "Jurisprudence and International Law"
  ],
  "College of Medicine": [
    "Medicine and Surgery",
    "Nursing Science",
    "Medical Rehabilitation (Physiotherapy)",
    "Medical Laboratory Science",
    "Radiography",
    "Anatomy",
    "Physiology"
  ],
  "Others": ["General Studies", "Foundation Program", "Custom Department"]
};
