export const DID_YOU_KNOW_WORDS = [
  "Active Recall is the single most effective way to lock information into your long-term memory.",
  "Spaced Repetition exploits the psychological spacing effect to prevent the 'forgetting curve'.",
  "The Feynman Technique involves teaching a concept to a child to find gaps in your own knowledge.",
  "The Pomodoro Technique uses 25-minute focus intervals followed by 5-minute breaks to sustain mental stamina.",
  "Sleep consolidation converts short-term study experiences into permanent long-term memory traces.",
  "Neuroplasticity is the brain's incredible capacity to physically restructure itself as you acquire new skills.",
  "Interleaving is studying related but different topics together to build deeper cognitive agility.",
  "The Zeigarnik Effect states that our brains remember uncompleted tasks better than completed ones.",
  "Dual Coding Theory shows that combining words with visual imagery increases retention by 200%.",
  "Hydration directly impacts brain speed; even mild dehydration can impair concentration by 15%.",
  "The Protégé Effect reveals that students who teach others show much higher mastery than peers who do not.",
  "BDNF (Brain-Derived Neurotrophic Factor) is a protein boosted by exercise that acts as fertilizer for brain cells.",
  "A 20-minute power nap can restore cognitive focus and enhance memory retention by up to 40%.",
  "Writing study notes by hand activates more complex neural pathways for reading than typing on a keyboard.",
  "The Leitner System is a highly structured flashcard organization method based on spaced repetition intervals.",
  "Overlearning—continuing to study after reaching initial mastery—helps make recall automatic under high stress.",
  "Mnemonic devices use association, rhythm, and imagery to make abstract concepts instantly memorable.",
  "Our working memory can typically hold only 4 to 7 pieces of information at a single time.",
  "Chunking is the process of grouping individual pieces of info into larger, meaningful cognitive units.",
  "Testing yourself frequently is up to three times more powerful than simply re-reading your textbook.",
  "The forgetting curve was discovered by Hermann Ebbinghaus, showing memory decay is steepest in the first 24 hours.",
  "Blue light from screens suppresses melatonin release, disrupting the deep sleep cycle needed for memory storage.",
  "Elaborative Rehearsal is connecting new information to existing knowledge to build rich cognitive webs.",
  "Studying in different rooms or changing environments enhances recall flexibility during exams.",
  "Listening to instrumental background music like Lo-Fi or classical can help maintain task-oriented focus.",
  "The self-reference effect makes you remember details better when you relate them directly to your own life.",
  "The Primacy Effect shows that the first few items in a study list are more likely to be remembered.",
  "The Recency Effect means you are highly likely to recall information studied at the very end of a session.",
  "Grit—the passion and perseverance for long-term goals—is a better predictor of academic success than IQ.",
  "Distributed Practice is breaking study time into small, regular sessions rather than one massive cramming session.",
  "Metacognition is 'thinking about thinking'—being aware of how well you understand what you are studying.",
  "Mind mapping helps visualize connections between ideas, aligning perfectly with our brain's radiant thinking.",
  "The testing effect proves that the act of retrieving information physically strengthens neural pathways.",
  "Physical exercise increases the size of the hippocampus, the brain area involved in verbal memory and learning.",
  "Flashcards are most effective when they require active generation of answers, not just recognition.",
  "The spacing effect shows that study intervals should double in length each time you successfully recall the fact.",
  "Eating dark chocolate increases blood flow to the brain, improving verbal memory and visual spatial skills.",
  "Deep breathing increases oxygen delivery to brain cells, instantly reducing exam anxiety and tension.",
  "An organized study desk reduces cognitive load, allowing your brain to focus entirely on the material.",
  "Stretching during study breaks improves blood circulation, delivering fresh glucose to tired brain cells.",
  "The Blurting Method involves reading a page, closing the book, and writing down everything you can remember.",
  "Cornell Notes utilize a structured format of notes, cues, and a summary to drive interactive review.",
  "Self-explanation—explaining to yourself why a step or concept is correct—deepens logical comprehension.",
  "A high-protein breakfast helps stabilize neurotransmitters, preventing mid-morning cognitive crashes.",
  "Pre-testing—taking a test on material before you study it—actually improves your learning when you do study.",
  "The generation effect shows that information you produce yourself is remembered better than read info.",
  "Visual metaphors help translate abstract mathematical or scientific formulas into easy-to-recall stories.",
  "Teaching a study partner or explaining a concept aloud engages verbal and motor memory pathways simultaneously.",
  "Micro-learning—studying in 5-minute bite-sized bursts—is ideal for memorizing quick facts and vocabulary.",
  "Cognitive overload happens when the volume of study material exceeds your working memory capacity.",
  "The keyword method uses a visual image connecting a new foreign word with a similar-sounding familiar word.",
  "Spaced retrieval combined with active recall is the gold standard of modern cognitive science education.",
  "Taking a walk in nature can reduce brain fatigue and dramatically restore focused attention levels.",
  "The peak-end rule means you will remember a study session based on its hardest part and how it finished.",
  "Retrieval cues are internal prompts (like a smell, sound, or feeling) that help unlock stored memories.",
  "Memory encoding is the initial process of transforming sensory input into a form your brain can store.",
  "Using a red pen for corrections helps your brain register and remember errors more vividly.",
  "A cold glass of water upon waking up rehydrates your brain, immediately boosting morning mental alertness.",
  "A study buddy can provide accountability, ensuring you stay committed to your daily learning goals.",
  "Structuring information in a hierarchy (broad concepts down to details) matches our brain's storage design.",
  "A study timer helps create a sense of urgency, boosting focus and reducing procrastination.",
  "The sensory memory store retains sensory impressions for less than a second before passing them to working memory.",
  "Context-dependent memory suggests that studying under the same conditions as your exam improves score output.",
  "Practicing in the evening right before sleep allows the brain to optimize consolidation during the night.",
  "Synthesizing information from three different sources forces your brain to build a comprehensive view of a topic.",
  "Taking structured breaks prevents cognitive saturation, keeping your absorbing capacity high.",
  "The placebo effect can actually boost exam performance if you truly believe in your study system.",
  "Using multiple colors in your diagrams helps the visual cortex organize and segregate complex subsystems.",
  "Reflective journaling at the end of a week highlights which study strategies worked best for you.",
  "Doodling related concepts during a lecture can actually prevent your mind from drifting into daydreaming.",
  "The best study schedule is a flexible calendar that blocks energy peaks for the hardest cognitive tasks.",
  "Laughter releases endorphins, lowering stress hormones that block your brain's memory retrieval systems.",
  "The brain uses 20% of your body's total energy, despite representing only 2% of your overall weight.",
  "Omega-3 fatty acids are critical for maintaining healthy brain cell membranes and cognitive performance.",
  "Deep sleep is when the brain flushes out metabolic waste, acting as a natural neural reset.",
  "Consistently setting specific, measurable study goals increases your likelihood of achieving them by 50%.",
  "The law of association means our brain stores new facts by anchoring them to things we already know.",
  "Failing mock tests is highly beneficial; errors create a strong neural signal to pay closer attention next time.",
  "The average attention span for focused study is 20 to 45 minutes before mental efficiency dips.",
  "Affirmations combined with preparation boost exam confidence, reducing cortisol levels under pressure.",
  "Varying your studying speed—skimming first, then reading deeply—enhances overall text absorption.",
  "The SQ3R method stands for Survey, Question, Read, Recite, Review—a complete active reading strategy.",
  "Anxiety blocks the prefrontal cortex, which is why students 'blank out' on exams despite studying hard.",
  "Mnemonics based on absurd or funny mental pictures are retained far longer than logical associations.",
  "A short mindfulness meditation before studying stabilizes brainwaves and enhances focus capacity.",
  "The brain's left hemisphere is generally analytical, while the right hemisphere manages spatial and creative patterns.",
  "Taking regular deep-breathing breaks during exams lowers your heart rate, restoring calm thinking.",
  "The best way to memorize a list is to create a vivid story linking each item in a sequence.",
  "Retrieval practice is the opposite of cramming; it forces you to pull information out of your brain.",
  "Studying complex subjects in layers (overview, main pillars, then details) is called progressive disclosure.",
  "Using flashcards with minimal text on each card prevents visual overcrowding and aids rapid recall.",
  "The Pygmalion Effect states that higher expectations lead to an increase in academic performance.",
  "Our brains are highly responsive to curiosity; asking questions before reading activates eager learning networks.",
  "Solving past papers is the closest simulation to the actual exam, training your brain for pressure.",
  "An optimal study light mimics natural daylight, reducing eye strain and keeping melatonin at bay.",
  "Positive self-talk during difficult math problems prevents the brain's defense mechanism from giving up.",
  "Taking notes in your own words ensures that your brain has actually processed and digested the meaning.",
  "The brain cannot truly multitask; switching between studying and texting reduces focus efficiency by 40%.",
  "Your brain continues to solve complex study problems in the background while you are doing mechanical chores.",
  "Consuming green tea provides L-theanine and caffeine, a combination that boosts calm alertness.",
  "The word 'Mnemonic' originates from Mnemosyne, the ancient Greek goddess of memory.",
  "Flashcards should be shuffled regularly to avoid serial position bias (memorizing cards in a fixed order).",
  "Active recall is not just for exams; it is the key to mastering languages, instruments, and professional skills.",
  "The hippocampus act as a temporary routing station; memories are eventually transferred to the neocortex.",
  "Studying with a clean physical setup prevents visual distractions from competing for your attention.",
  "Making your own flashcards is twice as effective as using pre-made decks, due to the encoding effect.",
  "Micro-rewards (e.g., a short walk, a healthy snack) after completing a task reinforce positive study habits.",
  "The Leitner card system uses physical boxes to track card review frequencies based on accuracy.",
  "The word 'university' comes from the Latin 'universitas', meaning a community of teachers and scholars.",
  "Listening to white noise can help filter out ambient household distractions during deep study.",
  "Reviewing your notes for just 10 minutes within 24 hours of a lecture prevents 80% of memory loss.",
  "Using a pointer or finger while reading helps keep your eyes tracked, increasing reading speed.",
  "The brain's visual cortex is massive, which is why visual diagrams are processed 60,000 times faster than text.",
  "Taking a quick walk after memorizing vocabulary helps cement the words in your memory.",
  "The Pomodoro technique is named after a tomato-shaped kitchen timer used by its creator, Francesco Cirillo.",
  "A study room with a temperature of 21-22°C (70-72°F) is considered optimal for sustained concentration.",
  "The term 'Cramming' leads to rapid forgetting because it does not allow neural connections to consolidate.",
  "Reading aloud improves retention because you are both seeing and hearing the words (the production effect).",
  "The brain develops most of its synapses during early childhood, but learning keeps synaptic plasticity alive.",
  "Using analogies connects unfamiliar scientific concepts to simple daily occurrences, simplifying review.",
  "The 'Goldilocks' study task is one that is neither too easy (boredom) nor too hard (frustration).",
  "Blue-light blocking glasses can help prevent digital eye strain during late-night laptop study.",
  "To remember a difficult spelling, create a short sentence where the first letter of each word spells it out.",
  "A regular sleep schedule is more beneficial for grades than an all-night cramming session.",
  "Deep learning requires emotional engagement; finding a personal connection to a topic boosts retention.",
  "Setting a specific time for studying daily builds a powerful habit, reducing the need for willpower.",
  "The 'rubber duck' debugging method involves explaining a problem step-by-step to an inanimate object.",
  "Taking mock exams under real time limits trains your brain to manage clock-based stress effectively.",
  "The forgetting curve is exponential, meaning the loss of information is extremely rapid initially.",
  "High cortisol (stress) levels physically shrink the hippocampus over time, impairing learning.",
  "The word 'scholar' stems from the Greek 'schole', which originally meant 'leisure' or free time for learning.",
  "A 10-minute stretching routine can increase blood flow to the brain, releasing mental blocks.",
  "Explaining a hard theorem to a family member helps clarify your own logical structure.",
  "The brain's reward center releases dopamine when you successfully answer a difficult quiz question.",
  "Using digital flashcard apps allows you to study anywhere, converting idle commute times into learning sessions.",
  "Our brain is a pattern-seeking organ; creating categories for facts makes them much easier to store.",
  "A study tracker helps visualize your progress, building powerful momentum and study streaks.",
  "The 'Feynman Notebook' is a dedicated book where you simplify and deconstruct highly complex concepts.",
  "Reading a summary of a chapter before reading the full text gives your brain a roadmap for key ideas.",
  "Physical index cards provide a tactile experience that some students find superior to digital screens.",
  "A light snack of nuts and berries during study breaks provides sustained energy without a sugar crash.",
  "The 'illusion of competence' occurs when you read notes and think you know them, without testing yourself.",
  "Breaking a massive project into 'micro-tasks' prevents the initial overwhelm that causes procrastination.",
  "The word 'academy' comes from the garden of Academus in Athens, where Plato taught his students.",
  "Scribbling down key points in a margin while reading keeps you active and prevents passive eyes.",
  "Memory palaces associate facts with rooms in a physical house you know well, a technique from ancient Greece.",
  "An average human brain can store up to 2.5 petabytes of data—equivalent to 3 million hours of TV.",
  "Taking a 5-minute quiet break without any phone screens allows the brain to consolidate what was just read.",
  "The 'spacing interval' should expand: review in 1 day, then 3 days, 7 days, 14 days, and 30 days.",
  "Active recall triggers the prefrontal cortex, which is responsible for executive decision-making.",
  "The Feynman technique forces you to strip away complex jargon, proving whether you truly understand.",
  "Classical music has been shown to increase spatial-temporal reasoning performance (the Mozart Effect).",
  "A messy desktop increases visual noise, causing your brain to expend energy filtering out clutter.",
  "Vocalizing your thoughts while solving complex math equations reduces calculation errors by 30%.",
  "A good study session is determined by quality and focus, not the raw number of hours sat.",
  "Taking notes using a mind-mapping tool visualizes the structural hierarchy of a course's curriculum.",
  "The brain's prefrontal cortex is not fully developed until age 25, affecting planning and study habits.",
  "Re-reading a textbook chapter has a near-zero utility score for long-term retention compared to self-quizzing.",
  "To master a new language, focus on the 1000 most common words first to unlock 80% of comprehension.",
  "The Leitner System was developed by German science journalist Sebastian Leitner in 1972.",
  "Laying out all study materials the night before removes friction, making it easier to start the next morning.",
  "Cognitive flexibility is the ability to switch between thinking about two different concepts.",
  "Your brain has roughly 86 billion neurons, each connected to thousands of others in an intricate web.",
  "Taking a quick shower during a study block can stimulate creative ideas and release mental fatigue.",
  "The word 'matriculation' comes from the Latin 'matricula', meaning a public register of student names.",
  "Writing a daily to-do list with only 3 high-priority tasks ensures you focus on what truly matters.",
  "Using visual schemas (like flowcharts) simplifies the learning of long biological or mechanical processes.",
  "The 'forgetting curve' is flattened each time you actively retrieve the information from memory.",
  "Resting your eyes for 60 seconds during intensive reading sessions prevents physical strain and headaches.",
  "A high-quality mattress is a secret study tool; sleep quality determines how well you retain facts.",
  "The Pomodoro technique helps manage the 'planning fallacy' by tracking how long tasks actually take.",
  "The brain consumes about 120 grams of glucose daily as its primary fuel source.",
  "Studying immediately after light cardio can increase the absorption rate of abstract concepts.",
  "Visual flashcards that pair an image with a definition engage both visual and verbal memory.",
  "The self-explanation technique is highly recommended by cognitive scientists for mastering logical subjects.",
  "To break procrastination, use the '5-second rule': count down 5-4-3-2-1 and immediately start writing.",
  "The best study playlist has no lyrics; words in songs compete for your brain's language processing centers.",
  "A dynamic study checklist gives you a satisfying dopamine release every time you cross an item off.",
  "Using physical movement (like gesturing or walking) while reciting notes aids kinesthetic learners.",
  "The forgetting curve demonstrates that we forget 50% of new information within one hour of learning it.",
  "A dedicated study zone tells your brain 'it is time to work' the moment you sit down.",
  "The brain consolidates declarative memory (facts) during deep sleep and procedural memory (skills) during REM.",
  "To memorize a formula, write it out 5 times, then try to write it from memory 3 times.",
  "Using colored highlighters is only useful if you limit them to 10% of the text; over-highlighting blends everything.",
  "A study session with positive ambient lighting prevents drowsiness and keeps you mentally sharp.",
  "Taking notes by summarizing each slide in a single sentence forces you to synthesize meaning.",
  "The Greek philosopher Aristotle wrote that 'exercise in retrieving a memory keeping it alive'.",
  "The 'just-in-time' learning concept means learning a skill right when you need to apply it for max retention.",
  "A 15-minute screen-free study break gives your optic nerve a rest, reducing mental fatigue.",
  "Connecting new historical dates to events you already know helps anchor them securely in your timeline.",
  "Reading summaries before exams is great for refreshing, but active recall during the semester is what builds grades.",
  "Your brain's capacity for learning is virtually infinite; you never 'run out of room' for new information.",
  "The Cornell note-taking system was created at Cornell University in the 1940s by Walter Pauk.",
  "Using a checklist for study topics reduces the anxiety of not knowing where to start.",
  "A cold water splash on the face stimulates the vagus nerve, immediately slowing down exam panic.",
  "The best way to study is to assume you are going to be tested on the material in one hour.",
  "A study routine is built on cues: select a fixed time, a fixed place, and a satisfying reward.",
  "Mastering active study methods like retrieval and spacing is the ultimate superpower for lifelong learning!"
];
